#!/bin/bash
# Setup script for creating a separate GitHub Pages repo
# This will help you sync docs/ to a new public repo for GitHub Pages

set -e

REPO_NAME="${1:-EEIntake-Pages}"
GITHUB_USER="${2:-rc979}"

echo "=========================================="
echo "GitHub Pages Repo Setup"
echo "=========================================="
echo ""
echo "This script will help you create a new public repo for GitHub Pages."
echo "Repo name: $REPO_NAME"
echo "GitHub user: $GITHUB_USER"
echo ""
echo "Steps:"
echo "1. Create a new PUBLIC repo on GitHub:"
echo "   https://github.com/new"
echo "   Name: $REPO_NAME"
echo "   Visibility: Public"
echo "   DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating the repo, run:"
echo "   ./scripts/publish/sync_to_gh_pages.sh $REPO_NAME $GITHUB_USER"
echo ""
echo "Or manually:"
echo "   cd /tmp"
echo "   git clone https://github.com/$GITHUB_USER/$REPO_NAME.git"
echo "   cd $REPO_NAME"
echo "   cp -r \"$PWD/docs/\"* ."
echo "   git add ."
echo "   git commit -m 'Initial GitHub Pages deployment'"
echo "   git push"
echo ""
echo "3. Enable GitHub Pages:"
echo "   Go to: https://github.com/$GITHUB_USER/$REPO_NAME/settings/pages"
echo "   Source: Deploy from a branch"
echo "   Branch: main"
echo "   Folder: / (root)"
echo "   Click Save"
echo ""
echo "4. Your site will be available at:"
echo "   https://$GITHUB_USER.github.io/$REPO_NAME/"
echo ""
